name: Node API CI

on:
  push:
    branches:
      - main

jobs:

  api:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Start API
        run: |
          node index.js &
          sleep 5

      - name: Test endpoint
        run: |
          curl http://localhost:3000